### ISSUE TITLE
This is not target event.

### ISSUE THREAD

**Issue by janpio** [technote-space/toc-generator#63] opened 2019-09-30 15:33 UTC
Normal commits to our repo do not trigger TOC generation any more:

```
Run technote-space/toc-generator@v1

==================================================
Version:  v1.3.1
Event:    push
Action:   undefined
sha:      
ref:      
owner:    prisma
repo:     specs
actor:    janpio
==================================================

> This is not target event.
```

https://github.com/prisma/specs/pull/191/checks?check_run_id=241834689

**Comment by technote-space** [comment] 2019-09-30 16:15
Thank you for your issue.

I think the cause are these.
- https://github.community/t5/GitHub-Actions/GITHUB-REF-and-GITHUB-SHA-no-longer-work/m-p/33283/highlight/true#M1439
- https://github.community/t5/GitHub-Actions/PSA-GitHub-Actions-are-a-bit-broken-this-morning-missing-SHAs/m-p/33282#M1438

This seems to be happening in other GitHub Actions.
https://github.com/actions/checkout/issues/49

Please wait until it is fixed.

**Comment by janpio** [comment] 2019-09-30 18:13
Thanks for the reply - so we'll wait until GitHub reacts.

**Comment by technote-space** [comment] 2019-09-30 23:46
It seems to be working correctly, so I close this issue.
https://github.com/prisma/specs/commit/298c49d4dcbc19ed80e57eea2d12b1232dea618d/checks

- https://github.com/actions/checkout/issues/49#issuecomment-536658043
- https://github.community/t5/GitHub-Actions/GITHUB-REF-and-GITHUB-SHA-no-longer-work/m-p/33290#M1442

**Closed by technote-space** 2019-09-30 23:46 UTC
Labels: triage

**Comment by janpio** [comment] 2019-10-01 10:36
Thanks for the update.
